// <auto-generated />
namespace CrystalReportsMVC_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Employee_NotNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee_NotNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201901070850205_Employee_NotNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
